from mgl7460.tp1.types.traitements.definitions.condition_transition import ConditionTransition
from mgl7460.tp1.types.traitements.definitions.definition_tache import DefinitionTache
from mgl7460.tp1.types.traitements.definitions.definition_transition import DefinitionTransition


class DefinitionProcessus:

    def get_nom(self) -> str: ...

    def get_description(self) -> str: ...

    def set_description(self, description: str) -> None: ...

    def get_taches(self) -> list[DefinitionTache]: ...

    def ajouter_tache(self, definition_tache: DefinitionTache) -> None: ...

    def ajouter_transition(self, definition_transition: DefinitionTransition) -> None: ...

    def ajouter_transition_entre_taches(
        self,
        tache_source: DefinitionTache,
        tache_destination: DefinitionTache,
        condition_transition: ConditionTransition,
    ) -> None: ...

    def get_transitions_sortantes_de(self, tache: DefinitionTache) -> list[DefinitionTransition]: ...

    def get_premiere_tache(self) -> DefinitionTache: ...

    def set_premiere_tache(self, tache: DefinitionTache) -> None: ...

    def ajouter_premiere_tache(self, tache: DefinitionTache) -> None: ...

    def is_tache_finale(self, tache: DefinitionTache) -> bool: ...
