from typing import Protocol


class DemandeurPret(Protocol):

    def get_nom(self) -> str: ...

    def get_prenom(self) -> str: ...

    def get_nas(self) -> str: ...

    def get_revenu_annuel(self) -> float: ...

    def set_revenu_annuel(self, revenu: float) -> None: ...

    def get_obligations_annuelles(self) -> float: ...

    def set_obligations_annuelles(self, obligations: float) -> None: ...

    def get_taux_endettement(self) -> float: ...

    def get_score_credit(self) -> int: ...

    def set_score_credit(self, score: int) -> None: ...
