from datetime import datetime
from typing import Protocol

from mgl7460_tp1.types.modeles.demandeur_pret import DemandeurPret
from mgl7460_tp1.types.modeles.propriete import Propriete
from mgl7460_tp1.types.modeles.resultat_traitement import ResultatTraitement
from mgl7460_tp1.types.modeles.termes_pret import TermesPret


class DemandePret(Protocol):

    def get_numero_demande(self) -> str | None: ...

    def get_date_demande(self) -> datetime: ...

    def get_demandeur_pret(self) -> DemandeurPret: ...

    def get_propriete(self) -> Propriete: ...

    def get_montant_pret(self) -> float: ...

    def get_montant_mise_de_fonds(self) -> float: ...

    def set_montant_mise_de_fonds(self, montant: float) -> None: ...

    def get_resultat_traitement(self) -> ResultatTraitement: ...

    def set_resultat_traitement(
        self, resultat_traitement: ResultatTraitement
    ) -> None: ...

    def get_ratio_emprunt_valeur(self) -> float: ...

    def get_prix_achat(self) -> float: ...

    def set_prix_achat(self, prix: float) -> None: ...

    def get_termes_pret(self) -> TermesPret | None: ...

    def set_termes_pret(self, termes: TermesPret) -> None: ...
