from typing import Protocol

from mgl7460_tp1.types.traitements.definitions.traitement_tache import TraitementTache


class DefinitionTache(Protocol):

    def get_nom(self) -> str: ...

    def get_description(self) -> str: ...

    def set_description(self, description: str) -> None: ...

    def get_traitement_tache(self) -> TraitementTache | None: ...

    def set_traitement_tache(self, traitement: TraitementTache) -> None: ...
