from mgl7460_tp1.types.modeles.demande_pret import DemandePret
from mgl7460_tp1.types.traitements.definitions.definition_tache import DefinitionTache
from mgl7460_tp1.types.traitements.instances.etat_traitement import EtatTraitement
from mgl7460_tp1.types.traitements.instances.instance_processus import InstanceProcessus


class InstanceTache:

    def get_definition_tache(self) -> DefinitionTache: ...

    def get_etat_instance_tache(self) -> EtatTraitement: ...

    def set_etat_instance_tache(self, etat_traitement: EtatTraitement) -> None: ...

    def get_processus_englobant(self) -> InstanceProcessus: ...

    def get_demande_pret(self) -> DemandePret: ...

    def set_demande_pret(self, demande_pret: DemandePret) -> None: ...

    def executer(self) -> None: ...
