from datetime import datetime
from logging import Logger

from mgl7460_tp1.types.modeles.demande_pret import DemandePret
from mgl7460_tp1.types.traitements.definitions.definition_processus import DefinitionProcessus
from mgl7460_tp1.types.traitements.instances.etat_processus import EtatProcessus
from mgl7460_tp1.types.traitements.instances.instance_tache import InstanceTache


class InstanceProcessus:

    def get_demande_pret(self) -> DemandePret: ...

    def get_definition_processus(self) -> DefinitionProcessus: ...

    def get_etat_processus(self) -> EtatProcessus: ...

    def set_etat_processus(self, etat_processus: EtatProcessus) -> None: ...

    def get_tache_courante(self) -> InstanceTache: ...

    def set_tache_courante(self, tache_courante: InstanceTache) -> None: ...

    def demarrer(self) -> None: ...

    def get_temps_demarrage(self) -> datetime: ...

    def set_temps_arret(self, temps_arret: datetime) -> None: ...

    def signaler_fin_tache(self, instance_tache: InstanceTache) -> None: ...

    def get_logger(self) -> Logger: ...

    def set_logger(self, logger: Logger) -> None: ...
