from datetime import datetime
from logging import Logger
from typing import Protocol

from mgl7460_tp1.types.modeles.demande_pret import DemandePret
from mgl7460_tp1.types.traitements.instances.etat_processus import EtatProcessus
from mgl7460_tp1.types.traitements.instances.instance_tache import InstanceTache


class InstanceProcessus(Protocol):

    from mgl7460_tp1.types.traitements.definitions.definition_processus import DefinitionProcessus

    def get_demande_pret(self) -> DemandePret: ...

    def get_definition_processus(self) -> DefinitionProcessus: ...

    def get_etat_processus(self) -> EtatProcessus: ...

    def get_tache_courante(self) -> InstanceTache | None: ...

    def demarrer(self) -> None: ...

    def get_temps_demarrage(self) -> datetime | None: ...

    def get_temps_arret(self) -> datetime | None: ...

    def signaler_fin_tache(self, instance_tache: InstanceTache) -> None: ...

    def get_logger(self) -> Logger: ...

    def set_logger(self, logger: Logger) -> None: ...
